"""Create schema tables

Revision ID: dfad5df2737b
Revises: 
Create Date: 2026-10-02 03:16:52.946507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfad5df2737b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('referral_bonus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tesla_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tesla_messages_id'), 'tesla_messages', ['id'], unique=True)
    op.create_table('tesla_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tesla_users_id'), 'tesla_users', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('BITCOIN', 'ETHEREUM', 'BNB', 'PAYEE', 'TRON', 'USDT', 'USDTTRC', name='paymentmethods'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['investment_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tesla_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tesla_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tesla_cars_id'), 'tesla_cars', ['id'], unique=True)
    op.create_table('tesla_configurators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False),
    sa.Column('interior_color', sa.Enum('ALL_BLACK', 'BLACK_AND_WHITE', 'PREMIUM_TAN', name='interiorcolorenum'), nullable=False),
    sa.Column('exterior_color', sa.Enum('DEEP_BLUE_METALLIC', 'PEARL_WHITE_MULTI_COAT', 'SOLID_BLACK', 'RED_MULTI_COAT', 'MIDNIGHT_SHOW_METALLIC', 'QUANTUM_GRAY', name='exteriorcolorenum'), nullable=False),
    sa.Column('wheel', sa.Enum('AERO_19', 'SPORT_20', 'PERFORMANCE_21', 'TURBINE_22', name='wheelsenum'), nullable=False),
    sa.Column('packages', sa.Enum('PREMIUM_INTERIOR', 'ENHANCED_AUTOPILOT', 'FULL_SELF_DRIVING', 'COLD_WEATHER', 'TOWING', 'TRACK', name='packagesenum'), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tesla_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tesla_configurators_id'), 'tesla_configurators', ['id'], unique=True)
    op.create_table('test_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('vehicle_model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False),
    sa.Column('preferred_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_time', sa.DateTime(), nullable=False),
    sa.Column('preferred_location', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('crypto_currency', sa.Enum('BITCOIN', 'ETHEREUM', 'BNB', 'TRON', name='paymentmethod'), nullable=True),
    sa.Column('payment_status', sa.Enum('SUCCESS', 'PENDING', 'DECLINED', name='paymentstatus'), nullable=False),
    sa.Column('crypto_address', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tesla_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_drives_id'), 'test_drives', ['id'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('BITCOIN', 'ETHEREUM', 'BNB', 'PAYEE', 'TRON', 'USDT', 'USDTTRC', name='paymentmethods'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_test_drives_id'), table_name='test_drives')
    op.drop_table('test_drives')
    op.drop_index(op.f('ix_tesla_configurators_id'), table_name='tesla_configurators')
    op.drop_table('tesla_configurators')
    op.drop_index(op.f('ix_tesla_cars_id'), table_name='tesla_cars')
    op.drop_table('tesla_cars')
    op.drop_table('profiles')
    op.drop_table('investments')
    op.drop_table('deposits')
    op.drop_table('users')
    op.drop_index(op.f('ix_tesla_users_id'), table_name='tesla_users')
    op.drop_table('tesla_users')
    op.drop_index(op.f('ix_tesla_messages_id'), table_name='tesla_messages')
    op.drop_table('tesla_messages')
    op.drop_table('messages')
    op.drop_table('investment_plans')
    # ### end Alembic commands ###
