"""recreate_tesla_cars_with_model

Revision ID: e0479ff152bb
Revises: 9c19a81a8d3b
Create Date: 2026-09-29 23:42:44.815341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0479ff152bb'
down_revision: Union[str, Sequence[str], None] = '9c19a81a8d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tesla_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tesla_cars_id'), 'tesla_cars', ['id'], unique=True)
    op.add_column('tesla_configurators', sa.Column('model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False))
    op.add_column('test_drives', sa.Column('vehicle_model', sa.Enum('TESLA_NEURALINK_V1', 'TESLA_NEURALINK_X', 'TESLA_NEURALINK_GT', name='carmodelenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_drives', 'vehicle_model')
    op.drop_column('tesla_configurators', 'model')
    op.drop_index(op.f('ix_tesla_cars_id'), table_name='tesla_cars')
    op.drop_table('tesla_cars')
    # ### end Alembic commands ###
